import * as pulumi from "@pulumi/pulumi";
import * as gcp from "@pulumi/gcp";
import { Iam } from "../iam";

const NAME_REGEX = /^[a-z]([-a-z0-9]*[a-z0-9])?$/;

/**
 * Frontend protocol configuration.
 *
 * @param type Frontend protocol: "HTTP" or "HTTPS"
 * @param certificateMap Short name of a certificate map (required when type is HTTPS); expanded to the full certificate-manager resource path
 */
export interface LoadBalancerProtocol {
    type: string;
    certificateMap?: pulumi.Input<string>;
}

/**
 * Frontend IP address configuration.
 *
 * @param type "ephemeral" (default) or "static"
 * @param addressName Name of a reserved global external address (required when type is static)
 */
export interface LoadBalancerIpAddress {
    type?: string;
    addressName?: pulumi.Input<string>;
}

/**
 * A single load balancer frontend (target proxy + global forwarding rule).
 *
 * @param description Optional description (default: "Frontend <key> for <name>")
 * @param protocol Protocol configuration
 * @param ipVersion "IPv4" (default) or "IPv6"
 * @param ipAddress IP address configuration (default: ephemeral)
 * @param port Forwarding rule port (default: 80 for HTTP, 443 for HTTPS)
 */
export interface LoadBalancerFrontend {
    description?: string;
    protocol: LoadBalancerProtocol;
    ipVersion?: string;
    ipAddress?: LoadBalancerIpAddress;
    port?: number;
}

/**
 * Cloud CDN cache TTL settings (all default to 3600 seconds).
 *
 * @param clientTTL Client TTL in seconds
 * @param defaultTTL Default TTL in seconds
 * @param maximumTTL Maximum TTL in seconds
 */
export interface LoadBalancerCdnCacheSettings {
    clientTTL?: number;
    defaultTTL?: number;
    maximumTTL?: number;
}

/**
 * Cloud CDN configuration for a bucket backend.
 *
 * @param enabled Whether Cloud CDN is enabled
 * @param cacheStaticContentSettings Cache TTL settings (used when enabled)
 */
export interface LoadBalancerCloudCdn {
    enabled?: boolean;
    cacheStaticContentSettings?: LoadBalancerCdnCacheSettings;
}

/**
 * Bucket backend configuration.
 *
 * @param description Optional description (default: "Backend <key> for <name>")
 * @param bucketName Name of the existing Cloud Storage bucket to serve
 */
export interface LoadBalancerBucketBackend {
    description?: string;
    bucketName: pulumi.Input<string>;
}

/**
 * A single load balancer backend. Only bucket backends are supported.
 *
 * @param bucket Bucket backend configuration
 * @param cloudCDN Optional Cloud CDN configuration
 */
export interface LoadBalancerBackend {
    bucket: LoadBalancerBucketBackend;
    cloudCDN?: LoadBalancerCloudCdn;
}

/**
 * A routing rule for a single host. `rule` conforms to
 * `gcp.types.input.compute.URLMapPathMatcher` (minus `name`, generated by the
 * module). Its `defaultService`, `pathRules[].service`, and `routeRules[].service`
 * fields reference backend keys, resolved to backend bucket self-links.
 *
 * @param rule The path matcher specification (minus `name`)
 */
export interface LoadBalancerRule {
    rule: gcp.types.input.compute.URLMapPathMatcher;
}

/**
 * Routing configuration for the load balancer's single URL map.
 *
 * @param mode Only "advancedHostAndPathRule" is supported
 * @param defaultBackend Backend key that receives unmatched traffic
 * @param rules Optional per-host path matchers, keyed by hostname
 */
export interface LoadBalancerRouting {
    mode: string;
    defaultBackend: string;
    rules?: { [host: string]: LoadBalancerRule };
}

/**
 * Global external application load balancer configuration.
 *
 * @param frontend Frontends keyed by frontend key (at least one)
 * @param backend Backends keyed by backend key (at least one)
 * @param routing Routing configuration
 */
export interface LoadBalancerRegionGlobal {
    frontend: { [key: string]: LoadBalancerFrontend };
    backend: { [key: string]: LoadBalancerBackend };
    routing: LoadBalancerRouting;
}

/**
 * External load balancer type. Only `regionGlobal` is supported.
 */
export interface LoadBalancerExternal {
    regionGlobal: LoadBalancerRegionGlobal;
}

/**
 * Application load balancer type. Only `external` is supported.
 */
export interface LoadBalancerApplication {
    external: LoadBalancerExternal;
}

/**
 * Load balancer type discriminator. Only `application` is supported.
 */
export interface LoadBalancerType {
    application: LoadBalancerApplication;
}

/**
 * Input arguments for the LoadBalancer module.
 *
 * @param name GCP resource name prefix (^[a-z]([-a-z0-9]*[a-z0-9])?$, max 63 chars)
 * @param project GCP project ID string
 * @param type Load balancer type configuration (application → external → regionGlobal)
 * @param labels Optional labels merged per [CONV-LABELS] (applied to resources that support labels)
 */
export interface LoadBalancerArgs {
    name: string;
    project: pulumi.Input<string>;
    type: LoadBalancerType;
    labels?: pulumi.Input<{ [key: string]: string }>;
}

/**
 * A Pulumi ComponentResource that creates a GCP global external application load
 * balancer (latest generation) with bucket backends: backend buckets (optionally
 * Cloud CDN enabled), a single URL map with advanced host/path routing, and one
 * target proxy + global forwarding rule per frontend.
 *
 * @param name The unique name of the component resource
 * @param args The load balancer creation arguments
 * @param opts Optional Pulumi resource options
 * @returns A LoadBalancer component with registered outputs
 */
export class LoadBalancer extends pulumi.ComponentResource {
    public readonly ipAddresses: { [frontendKey: string]: pulumi.Output<string> };
    public readonly urlMapSelfLink: pulumi.Output<string>;
    public readonly forwardingRuleSelfLinks: { [frontendKey: string]: pulumi.Output<string> };
    public readonly labels: pulumi.Output<{ [key: string]: string }>;

    constructor(name: string, args: LoadBalancerArgs, opts?: pulumi.ComponentResourceOptions) {
        super("custom:modules:LoadBalancer", name, {}, opts);

        this.validateArgs(args);

        const rg = args.type.application.external.regionGlobal;
        const mergedLabels = this.mergeLabels(args.labels);

        // LB service agent that reads private origin buckets (auto-created with compute.googleapis.com).
        const projectNumber = gcp.organizations.getProjectOutput({ projectId: args.project }, { parent: this }).number;
        const lbServiceAccount = pulumi.interpolate`serviceAccount:service-${projectNumber}@https-lb.iam.gserviceaccount.com`;

        const backendSelfLinks: { [key: string]: pulumi.Output<string> } = {};
        for (const [key, backend] of Object.entries(rg.backend)) {
            const cdnEnabled = backend.cloudCDN?.enabled === true;
            const cache = backend.cloudCDN?.cacheStaticContentSettings ?? {};

            const backendBucket = new gcp.compute.BackendBucket(`${name}-${key}-backend`, {
                name: `${args.name}-${key}-bucket`,
                project: args.project,
                description: backend.bucket.description ?? `Backend ${key} for ${args.name}`,
                bucketName: backend.bucket.bucketName,
                enableCdn: cdnEnabled,
                cdnPolicy: cdnEnabled
                    ? {
                          cacheMode: "CACHE_ALL_STATIC",
                          clientTtl: cache.clientTTL ?? 3600,
                          defaultTtl: cache.defaultTTL ?? 3600,
                          maxTtl: cache.maximumTTL ?? 3600,
                      }
                    : undefined,
            }, { parent: this });

            backendSelfLinks[key] = backendBucket.selfLink;

            new Iam(`${name}-${key}-bucket-iam`, {
                resource: { type: "storage", identifier: backend.bucket.bucketName },
                bindings: {
                    "roles/storage.objectViewer": [lbServiceAccount],
                },
            }, { parent: this });
        }

        const resolveBackend = (key: string): pulumi.Output<string> => {
            const selfLink = backendSelfLinks[key];
            if (!selfLink) {
                throw new Error(
                    `Backend key '${key}' referenced in routing does not match any backend. Known backends: ${Object.keys(backendSelfLinks).join(", ")}.`
                );
            }
            return selfLink;
        };

        const hostRules: gcp.types.input.compute.URLMapHostRule[] = [];
        const pathMatchers: gcp.types.input.compute.URLMapPathMatcher[] = [];
        if (rg.routing.rules) {
            for (const [host, entry] of Object.entries(rg.routing.rules)) {
                const matcherName = `${args.name}-${this.hostSlug(host)}`;
                hostRules.push({ hosts: [host], pathMatcher: matcherName });
                pathMatchers.push({
                    ...this.resolvePathMatcher(entry.rule, resolveBackend),
                    name: matcherName,
                });
            }
        }

        const urlMap = new gcp.compute.URLMap(`${name}-urlmap`, {
            name: `${args.name}-urlmap`,
            project: args.project,
            defaultService: resolveBackend(rg.routing.defaultBackend),
            hostRules: hostRules.length > 0 ? hostRules : undefined,
            pathMatchers: pathMatchers.length > 0 ? pathMatchers : undefined,
        }, { parent: this });

        const ipAddresses: { [frontendKey: string]: pulumi.Output<string> } = {};
        const forwardingRuleSelfLinks: { [frontendKey: string]: pulumi.Output<string> } = {};

        for (const [key, frontend] of Object.entries(rg.frontend)) {
            const isHttps = frontend.protocol.type.toUpperCase() === "HTTPS";
            const port = frontend.port ?? (isHttps ? 443 : 80);
            const ipVersion = (frontend.ipVersion ?? "IPv4") === "IPv6" ? "IPV6" : "IPV4";

            let targetSelfLink: pulumi.Output<string>;
            if (isHttps) {
                const certificateMap = pulumi.interpolate`//certificatemanager.googleapis.com/projects/${args.project}/locations/global/certificateMaps/${frontend.protocol.certificateMap}`;
                const proxy = new gcp.compute.TargetHttpsProxy(`${name}-${key}-proxy`, {
                    name: `${args.name}-${key}-proxy`,
                    project: args.project,
                    urlMap: urlMap.selfLink,
                    certificateMap: certificateMap,
                }, { parent: this });
                targetSelfLink = proxy.selfLink;
            } else {
                const proxy = new gcp.compute.TargetHttpProxy(`${name}-${key}-proxy`, {
                    name: `${args.name}-${key}-proxy`,
                    project: args.project,
                    urlMap: urlMap.selfLink,
                }, { parent: this });
                targetSelfLink = proxy.selfLink;
            }

            // ipVersion cannot be set alongside a reserved ipAddress; static references it by name.
            let staticAddress: pulumi.Output<string> | undefined;
            if (frontend.ipAddress?.type === "static") {
                staticAddress = gcp.compute
                    .getGlobalAddressOutput({ name: frontend.ipAddress.addressName!, project: args.project }, { parent: this })
                    .selfLink;
            }

            const forwardingRule = new gcp.compute.GlobalForwardingRule(`${name}-${key}-fr`, {
                name: `${args.name}-${key}-fr`,
                project: args.project,
                target: targetSelfLink,
                portRange: String(port),
                ipProtocol: "TCP",
                loadBalancingScheme: "EXTERNAL_MANAGED",
                labels: mergedLabels,
                ...(staticAddress ? { ipAddress: staticAddress } : { ipVersion }),
            }, { parent: this });

            ipAddresses[key] = forwardingRule.ipAddress;
            forwardingRuleSelfLinks[key] = forwardingRule.selfLink;
        }

        this.ipAddresses = ipAddresses;
        this.urlMapSelfLink = urlMap.selfLink;
        this.forwardingRuleSelfLinks = forwardingRuleSelfLinks;
        this.labels = mergedLabels;

        this.registerOutputs({
            ipAddresses: this.ipAddresses,
            urlMapSelfLink: this.urlMapSelfLink,
            forwardingRuleSelfLinks: this.forwardingRuleSelfLinks,
            labels: this.labels,
        });
    }

    /**
     * Returns a copy of the path matcher with backend keys resolved to backend
     * bucket self-links in `defaultService`, `pathRules[].service`, and
     * `routeRules[].service`.
     *
     * @param rule The path matcher specification (backend keys as service values)
     * @param resolve Resolver from backend key to backend bucket self-link
     * @returns The path matcher with resolved service self-links
     */
    private resolvePathMatcher(
        rule: gcp.types.input.compute.URLMapPathMatcher,
        resolve: (key: string) => pulumi.Output<string>,
    ): gcp.types.input.compute.URLMapPathMatcher {
        const source = rule as any;
        const resolved: any = { ...source };

        if (source.defaultService !== undefined) {
            resolved.defaultService = resolve(this.backendKey(source.defaultService));
        }
        if (Array.isArray(source.pathRules)) {
            resolved.pathRules = source.pathRules.map((pr: any) =>
                pr?.service !== undefined ? { ...pr, service: resolve(this.backendKey(pr.service)) } : pr
            );
        }
        if (Array.isArray(source.routeRules)) {
            resolved.routeRules = source.routeRules.map((rr: any) =>
                rr?.service !== undefined ? { ...rr, service: resolve(this.backendKey(rr.service)) } : rr
            );
        }
        return resolved;
    }

    /**
     * Asserts a routing service reference is a plain backend-key string.
     *
     * @param value The service reference value
     * @returns The backend key string
     */
    private backendKey(value: unknown): string {
        if (typeof value !== "string") {
            throw new Error(
                "Routing backend references (defaultService / service) must be plain backend-key strings, not raw GCP resource paths."
            );
        }
        return value;
    }

    /**
     * Converts an FQDN host (which may contain dots or a wildcard) into a stable,
     * resource-name-safe slug (e.g. "*.example.com" → "wildcard-example-com").
     *
     * @param host The hostname
     * @returns A deterministic slug of lowercase alphanumerics separated by hyphens
     */
    private hostSlug(host: string): string {
        return host
            .toLowerCase()
            .replace(/\*/g, "wildcard")
            .replace(/[^a-z0-9]+/g, "-")
            .replace(/^-+|-+$/g, "");
    }

    /**
     * Collects the backend-key references used by a path matcher.
     *
     * @param rule The path matcher specification
     * @returns The referenced backend keys (string values only)
     */
    private collectServiceRefs(rule: any): string[] {
        const refs: string[] = [];
        if (typeof rule?.defaultService === "string") {
            refs.push(rule.defaultService);
        }
        if (Array.isArray(rule?.pathRules)) {
            for (const pr of rule.pathRules) {
                if (typeof pr?.service === "string") {
                    refs.push(pr.service);
                }
            }
        }
        if (Array.isArray(rule?.routeRules)) {
            for (const rr of rule.routeRules) {
                if (typeof rr?.service === "string") {
                    refs.push(rr.service);
                }
            }
        }
        return refs;
    }

    /**
     * Merges user labels with module defaults and validates per [CONV-LABELS].
     * Module defaults win on key collision.
     *
     * @param userLabels Optional user-provided labels
     * @returns The validated, merged label map
     */
    private mergeLabels(userLabels?: pulumi.Input<{ [key: string]: string }>): pulumi.Output<{ [key: string]: string }> {
        return pulumi.output(userLabels || {}).apply(l => {
            const merged: { [key: string]: string } = {
                ...l,
                module: "load-balancer",
                deployed_by: "pulumi",
            };
            const labelKeyRegex = /^[a-z][a-z0-9_-]*$/;
            const labelValueRegex = /^[a-z0-9_-]*$/;
            for (const [key, value] of Object.entries(merged)) {
                if (key.length > 63 || !labelKeyRegex.test(key)) {
                    throw new Error(
                        `Invalid label key '${key}'. Keys must be lowercase letters, digits, underscores, or hyphens, start with a lowercase letter, and be max 63 characters.`
                    );
                }
                if (value.length > 63 || !labelValueRegex.test(value)) {
                    throw new Error(
                        `Invalid label value '${value}' for key '${key}'. Values must be lowercase letters, digits, underscores, or hyphens and be max 63 characters.`
                    );
                }
            }
            return merged;
        });
    }

    /**
     * Validates a resource-name segment (used for frontend/backend keys).
     *
     * @param value The segment value
     * @param field The field label for error messages
     */
    private validateSegment(value: string, field: string): void {
        if (!value || value.length > 63 || !NAME_REGEX.test(value)) {
            throw new Error(
                `'${field}' must match ^[a-z]([-a-z0-9]*[a-z0-9])?$ and be max 63 characters. Got '${value}'.`
            );
        }
    }

    /**
     * Validates the input arguments. Syntax-level validation only at construction
     * time; unresolved Outputs are skipped, and existence is deferred to the GCP
     * API at apply time.
     *
     * @param args The load balancer arguments to validate
     */
    private validateArgs(args: LoadBalancerArgs): void {
        if (!args.name || args.name.length > 63 || !NAME_REGEX.test(args.name)) {
            throw new Error(
                `'name' must match ^[a-z]([-a-z0-9]*[a-z0-9])?$ and be max 63 characters. Got '${args.name}'.`
            );
        }

        if (typeof args.project === "string") {
            if (!args.project) {
                throw new Error("'project' must be provided.");
            }
            if (/^\d+$/.test(args.project)) {
                throw new Error(
                    `'project' must be a GCP project ID string (e.g. 'my-project-a1b2'), not a numeric project number. Got '${args.project}'.`
                );
            }
        }

        const application = args.type?.application;
        if (!application) {
            throw new Error("'type.application' must be provided. Only 'application' is supported.");
        }
        const external = application.external;
        if (!external) {
            throw new Error("'type.application.external' must be provided. Only 'external' is supported.");
        }
        const rg = external.regionGlobal;
        if (!rg) {
            throw new Error("'type.application.external.regionGlobal' must be provided. Only 'regionGlobal' is supported.");
        }

        const frontendKeys = Object.keys(rg.frontend ?? {});
        if (frontendKeys.length === 0) {
            throw new Error("'frontend' must contain at least one entry.");
        }
        for (const key of frontendKeys) {
            this.validateSegment(key, `frontend.${key}`);
            const frontend = rg.frontend[key];
            const protocol = frontend.protocol?.type;
            if (!protocol || !["HTTP", "HTTPS"].includes(protocol.toUpperCase())) {
                throw new Error(`'frontend.${key}.protocol.type' must be one of HTTP, HTTPS. Got '${protocol}'.`);
            }
            if (protocol.toUpperCase() === "HTTPS" && !frontend.protocol.certificateMap) {
                throw new Error(`'frontend.${key}.protocol.certificateMap' must be provided when protocol.type is HTTPS.`);
            }
            if (frontend.ipVersion != null && !["IPv4", "IPv6"].includes(frontend.ipVersion)) {
                throw new Error(`'frontend.${key}.ipVersion' must be one of IPv4, IPv6. Got '${frontend.ipVersion}'.`);
            }
            if (frontend.ipAddress) {
                if (frontend.ipAddress.type != null && !["ephemeral", "static"].includes(frontend.ipAddress.type)) {
                    throw new Error(`'frontend.${key}.ipAddress.type' must be one of ephemeral, static. Got '${frontend.ipAddress.type}'.`);
                }
                if (frontend.ipAddress.type === "static" && !frontend.ipAddress.addressName) {
                    throw new Error(`'frontend.${key}.ipAddress.addressName' must be provided when ipAddress.type is static.`);
                }
            }
            if (frontend.port != null && (!Number.isInteger(frontend.port) || frontend.port < 1 || frontend.port > 65535)) {
                throw new Error(`'frontend.${key}.port' must be an integer between 1 and 65535. Got '${frontend.port}'.`);
            }
        }

        const backendKeys = Object.keys(rg.backend ?? {});
        if (backendKeys.length === 0) {
            throw new Error("'backend' must contain at least one entry.");
        }
        for (const key of backendKeys) {
            this.validateSegment(key, `backend.${key}`);
            const backend = rg.backend[key];
            if (!backend.bucket) {
                throw new Error(`'backend.${key}.bucket' must be provided. Only 'bucket' backends are supported.`);
            }
            if (backend.bucket.bucketName == null || (typeof backend.bucket.bucketName === "string" && !backend.bucket.bucketName)) {
                throw new Error(`'backend.${key}.bucket.bucketName' must be provided.`);
            }
        }

        const routing = rg.routing;
        if (!routing) {
            throw new Error("'routing' must be provided.");
        }
        if (routing.mode !== "advancedHostAndPathRule") {
            throw new Error(`'routing.mode' must be 'advancedHostAndPathRule'. Got '${routing.mode}'.`);
        }
        if (!routing.defaultBackend || !backendKeys.includes(routing.defaultBackend)) {
            throw new Error(
                `'routing.defaultBackend' must reference a backend key. Got '${routing.defaultBackend}'. Known backends: ${backendKeys.join(", ")}.`
            );
        }
        if (routing.rules) {
            const hosts = Object.keys(routing.rules);
            if (hosts.length === 0) {
                throw new Error("'routing.rules', when provided, must contain at least one host entry.");
            }
            for (const host of hosts) {
                const entry = routing.rules[host];
                if (!entry || !entry.rule) {
                    throw new Error(`'routing.rules.${host}.rule' must be provided.`);
                }
                for (const ref of this.collectServiceRefs(entry.rule)) {
                    if (!backendKeys.includes(ref)) {
                        throw new Error(
                            `'routing.rules.${host}' references unknown backend '${ref}'. Known backends: ${backendKeys.join(", ")}.`
                        );
                    }
                }
            }
        }
    }
}
